# generated by datamodel-codegen:
#   filename:  open_payment_mandate.json
#   timestamp: 2026-04-28T00:39:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field

from .types import amount, merchant
from .types import payment_instrument as payment_instrument_1
from .types import pisp as pisp_1


class AllowedPayees(BaseModel):
    """
    Defines the set of possible payees.
    """

    type: Literal['payment.allowed_payees'] = Field(
        default='payment.allowed_payees', description='Constraint type identifier.'
    )
    allowed: list[merchant.Merchant] = Field(
        ...,
        description='Array of allowed Merchant objects.',
        json_schema_extra={'x-selectively-disclosable-array': True},
    )


class AmountRange(BaseModel):
    """
    Defines the valid range for the payment amount
    """

    type: Literal['payment.amount_range'] = Field(
        default='payment.amount_range', description='Constraint type identifier.'
    )
    currency: str = Field(..., description='ISO4217 Alpha-3 currency code.')
    max: int = Field(
        ..., description='Maximum allowed amount in minor (cents) unit of currency.'
    )
    min: int | None = Field(
        default=None,
        description='Minimal amount in minor (cents) unit of currency. If absent, there is no minimum.',
    )


class PaymentReference(BaseModel):
    """
    Constrains the payment to a specific checkout reference.
    """

    type: Literal['payment.reference'] = Field(
        default='payment.reference', description='Constraint type identifier.'
    )
    conditional_transaction_id: str = Field(
        ..., description='Digest of the associated Open Checkout Mandate.'
    )


class Frequency(Enum):
    """
    Frequency of allowed recurrences.
    """

    ON_DEMAND = 'ON_DEMAND'
    DAILY = 'DAILY'
    WEEKLY = 'WEEKLY'
    BIWEEKLY = 'BIWEEKLY'
    MONTHLY = 'MONTHLY'
    QUARTERLY = 'QUARTERLY'
    ANNUALLY = 'ANNUALLY'


class AgentRecurrence(BaseModel):
    """
    Provides conditions for the agent to reuse this Payment Mandate multiple times.
    """

    type: Literal['payment.agent_recurrence'] = Field(
        default='payment.agent_recurrence', description='Constraint type identifier.'
    )
    frequency: Frequency = Field(..., description='Frequency of allowed recurrences.')
    max_occurrences: int | None = Field(
        default=None, description='Maximum number of allowed occurrences.'
    )


class Budget(BaseModel):
    """
    Defines the maximum total amount that can be spent when using the payment.agent_recurrence constraint.
    """

    type: Literal['payment.budget'] = Field(
        default='payment.budget', description='Constraint type identifier.'
    )
    max: float = Field(..., description='Maximum amount for the budget.')
    currency: str = Field(
        ..., description='ISO4217 Alpha-3 defining the currency of the amount.'
    )


class ExecutionDate(BaseModel):
    """
    Defines the valid time window for the payment execution.
    """

    type: Literal['payment.execution_date'] = Field(
        default='payment.execution_date', description='Constraint type identifier.'
    )
    not_before: str | None = Field(
        default=None, description='Earliest valid execution date.'
    )
    not_after: str | None = Field(
        default=None, description='Latest valid execution date.'
    )


class AllowedPaymentInstruments(BaseModel):
    """
    Defines the set of possible payment instruments for this Payment Mandate.
    """

    type: Literal['payment.allowed_payment_instruments'] = Field(
        default='payment.allowed_payment_instruments',
        description='Constraint type identifier.',
    )
    allowed: list[payment_instrument_1.PaymentInstrument] = Field(
        ...,
        description='Array of allowed payment instruments.',
        json_schema_extra={'x-selectively-disclosable-array': True},
    )


class AllowedPisps(BaseModel):
    """
    Defines the set of Payment Initiation Service Providers (PISPs) authorized to facilitate the transaction.
    """

    type: Literal['payment.allowed_pisps'] = Field(
        default='payment.allowed_pisps', description='Constraint type identifier.'
    )
    allowed: list[pisp_1.PISP] = Field(..., description='Array of allowed PISPs.')


class OpenPaymentMandate(BaseModel):
    """
    Agreement between a user and an agent (or chain of agents) to authorize future payment actions.
    """

    vct: Literal['mandate.payment.open.1'] = Field(
        default='mandate.payment.open.1',
        description="Verifiable Credential Type claim as defined in SD-JWT. MUST be 'mandate.payment.open'.",
    )
    constraints: list[
        AgentRecurrence
        | AllowedPayees
        | AllowedPaymentInstruments
        | AllowedPisps
        | AmountRange
        | Budget
        | ExecutionDate
        | PaymentReference
    ] = Field(
        ...,
        description='Array of constraints that the future checkout action must abide by.',
    )
    cnf: dict[str, Any] = Field(
        ...,
        description='Confirmation claim as defined in RFC 7800 section 3.1. Used for key binding.',
    )
    payee: merchant.Merchant | None = Field(
        default=None, description='The merchant receiving the payment.'
    )
    payment_amount: amount.Amount | None = Field(
        default=None,
        description='Transaction amount object containing currency (ISO 4217 code, e.g., "USD") and amount (integer minor units per ISO 4217, e.g., 27999 = $279.99). Pre-set by the user at time of mandate creation.',
    )
    payment_instrument: payment_instrument_1.PaymentInstrument | None = Field(
        default=None, description='The payment instrument used.'
    )
    pisp: pisp_1.PISP | None = Field(
        default=None, description='The Payment Initiation Service Provider.'
    )
    execution_date: str | None = Field(
        default=None,
        description='ISO8601 date of execution of payment. When absent indicates immediate execution.',
    )
    risk_data: dict[str, Any] | None = Field(
        default=None,
        description='An map of relevant risk signals collected by the trusted surface at time of mandate creation.',
    )
    iat: int | None = Field(
        default=None, description='The creation timestamp as a Unix epoch.'
    )
    exp: int | None = Field(
        default=None, description='The expiration timestamp as a Unix epoch.'
    )
