# generated by datamodel-codegen:
#   filename:  payment_mandate.json
#   timestamp: 2026-04-28T00:39:38+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from .types import amount, merchant
from .types import payment_instrument as payment_instrument_1
from .types import pisp as pisp_1


class PaymentMandate(BaseModel):
    """
    Agreement from a User or an Agent to authorize a particular Payment action.
    """

    vct: Literal['mandate.payment.1'] = Field(
        default='mandate.payment.1',
        description="Verifiable Credential Type claim as defined in SD-JWT. MUST be 'mandate.payment'.",
    )
    transaction_id: str = Field(
        ...,
        description='base64url-encoded hash of the checkout_jwt field value, uniquely identifying the checkout associated with this. The hash algorithm used MUST be the same as the sd_hash field for this sd-jwt, or sha256 if absent.',
    )
    payee: merchant.Merchant = Field(
        ..., description='The merchant receiving the payment.'
    )
    pisp: pisp_1.PISP | None = Field(
        default=None, description='The Payment Initiation Service Provider.'
    )
    payment_amount: amount.Amount = Field(
        ...,
        description='Transaction amount object containing currency (ISO 4217 code, e.g., "USD") and amount (integer minor units per ISO 4217, e.g., 27999 = $279.99). Final value confirmed by the user.',
    )
    payment_instrument: payment_instrument_1.PaymentInstrument = Field(
        ..., description='The payment instrument used.'
    )
    execution_date: str | None = Field(
        default=None,
        description='ISO8601 date of execution of payment. When absent indicates immediate execution.',
    )
    risk_data: dict[str, Any] | None = Field(
        default=None,
        description='An map of relevant risk signals collected by the trusted surface at time of mandate creation.',
    )
    iat: int | None = Field(
        default=None, description='The creation timestamp as a Unix epoch.'
    )
    exp: int | None = Field(
        default=None, description='The expiration timestamp as a Unix epoch.'
    )
