# generated by datamodel-codegen:
#   filename:  types/merchant.json
#   timestamp: 2026-04-28T00:39:38+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Merchant(BaseModel):
    """
    Schema defining a Mechant object
    """

    id: str = Field(..., description='Unique identifier for the merchant.')
    name: str = Field(..., description='Human-readable name of the merchant.')
    website: str | None = Field(
        default=None, description='Website belonging to the merchant.'
    )
