# generated by datamodel-codegen:
#   filename:  checkout_mandate.json
#   timestamp: 2026-04-28T00:39:38+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class CheckoutMandate(BaseModel):
    """
    Agreement from a User or an Agent to authorize a particular Checkout action.
    """

    vct: Literal['mandate.checkout.1'] = Field(
        default='mandate.checkout.1',
        description="Verifiable Credential Type claim as defined in SD-JWT. MUST be 'mandate.checkout'.",
    )
    checkout_jwt: str = Field(
        ...,
        description='base64url-encoded serialized merchant-signed JWT of the Checkout payload.',
        json_schema_extra={'x-selectively-disclosable-field': True},
    )
    checkout_hash: str = Field(
        ...,
        description='base64url-encoded hash of the checkout_jwt field value, uniquely identifying this checkout. If this checkout mandate is presented as an sd-jwt and the _sd_alg field is present then the hash algorithm used MUST match the _sd_alg field. Otherwise, sha-256 MUST be used.',
    )
    iat: int | None = Field(
        default=None, description='The creation timestamp as a Unix epoch.'
    )
    exp: int | None = Field(
        default=None, description='The expiration timestamp as a Unix epoch.'
    )
